.PHONY: cppcheck

# ************* Common defines ********************
CPPFLAGS += -fPIC -pthread -pg -fexceptions
CFLAGS += -g
LDFLAGS += -L. -lm -shared

include Makefile.common
include Makefile.cpputest

OBJ_TINY_LOOPBACK = examples/linux/loopback/tiny_loopback.o

all: library

cppcheck:
	@cppcheck --force \
	    --enable=warning,style,performance,portability \
	    --suppress=information \
	    -q -I ./src \
	    --error-exitcode=1 src
	@echo "[DONE]"
